### ISSUE TITLE
vapply error

### ISSUE THREAD

**Issue by roderickslieker** [lvalcarcel/gmctool#2]
Hi, 

Really cool tool! We've got 7 RNA-seq samples, 4/3 per group. I created a txt file with Ensembl IDs in the first column and data in remaining columns and samplesheet that matches the column names. Uploading works fine, but when hitting the Single or Double kO button I get the following error:

Warning in processWidget(instance) :
  renderDataTable ignores ... arguments when expr yields a datatable object; see ?renderDataTable
[1] "/var/folders/lt/6mdp3yvd4_qbkxn0qrz7md_40000gp/T//RtmpCWs2Rh/c3732011a8c75e06e9d9b56d/0.txt"
[1] TRUE
[1] "relevel the tables"
Warning in processWidget(instance) :
  renderDataTable ignores ... arguments when expr yields a datatable object; see ?renderDataTable
[1] "Calculate =  1"
[1] "Processing the 97607 gMCSs for 7 samples:"
  |======================                                                                                                                                      |  14%Warning: Error in vapply: values must be length 1,
 but FUN(X[[35]]) result is length 0
  1: runApp

The localT2 option does work. Running on MacOS, R4.4.1. 

Any idea what is going on?

**Comment by lvalcarcel** [comment]
Hello @roderickslieker,

Are there any NaN values in the matrix data you're working with? Also, when you load the data, how many of the ENSEMBL IDs overlap with the gmctool database? The tool typically provides this information as a percentage.

If there are no NaN values, feel free to share the text file and the relevant groups with me, and I'll gladly help review any errors.

Best regards,
Luis

**Comment by roderickslieker** [comment]
Hi, I have verified that the tool works on my system with the example data and it does just to be sure and there are no NaNs. Our data contains 72.32% of the genes of the gMCS. Would that cause the issue? The data is exactly formatted the same as the example data.

**Comment by lvalcarcel** [comment]
Hi @roderickslieker ,

It seems that the 72.32% overlap of genes may not be sufficient for gmctool. When defining the ENSEMBL IDs, it's important to consider that certain gene symbols can correspond to different ENSEMBL IDs. You might want to experiment with the example dataset to increase the number of shared ENSEMBL IDs for better compatibility with gmctool.

If the error persists, feel free to share the text file and the relevant groups with me, and I'll gladly help review any errors.

Kind regards,
Luis

**Comment by roderickslieker** [comment]
Hi Luis, 
Tnx for thinking along! It turned out to be that insufficient genes are present. I went back to our raw data and this resulted in a 100% overlap and now it works!

Roderick
